import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Auto-generate sidebar from the docs folder structure
  wikiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;